# TUGAS 1 (Data Integration)

### Muhammad Abid As Sarofi (06211640000082)

In [130]:
### Data integration
import pandas as pd
import numpy as np

In [181]:
### Input Data dari EXCEL berdasarkan SHEET
fasilitas = pd.read_excel('tabel1.xls',sheet_name='fasilitas')
korbanjiwa = pd.read_excel('tabel1.xls',sheet_name='korbanjiwa')
rumah = pd.read_excel('tabel1.xls',sheet_name='rumah')

In [182]:
## Menjadikan ke Data Frame
fasilitas=pd.DataFrame(fasilitas)
korbanjiwa=pd.DataFrame(korbanjiwa)
rumah=pd.DataFrame(rumah)

In [183]:
## Memunculkan data fasilitas
fasilitas

    Kode Bencana             Jenis Bencana  Kesehatan  Peribadatan  Pendidikan
0            101                    Banjir         35          349         443
1            102             Tanah Longsor          7           27          26
2            103  Banjir dan Tanah Longsor          0            0           0
3            104          Gelombang Pasang          0            9           2
4            105           Putting Beliung         10           72          96
5            106                Kekeringan          0            0           0
6            107           Kebakaran Hutan          0            0           0
7            108                Gempa Bumi         38          113        1005
8            109                   Tsunami          0            0           0
9            110    Gempa Bumi dan Tsunami         22          327         265
10           111        Letusan Gunung Api          0            0           0

In [134]:
## Memunculkan data korbanjiwa
korbanjiwa

,Kode Bencana,Jenis Bencana,Meninggal & Hilang,Luka-luka,Menderita & mengungsi
0,101,Banjir,119,297,1453803
1,102,Tanah Longsor,167,142,38198
2,103,Banjir dan Tanah Longsor,0,0,0
3,104,Gelombang Pasang,0,5,114829
4,105,Putting Beliung,24,228,16019
5,106,Kekeringan,0,0,7798693
6,107,Kebakaran Hutan,4,4,586
7,108,Gempa Bumi,572,2002,483399
8,109,Tsunami,453,14059,41132
9,110,Gempa Bumi dan Tsunami,3475,4438,221450
10,111,Letusan Gunung Api,0,56,71424

In [135]:
#Memunculkan Data rumah
rumah

,Kode Bencana,Jenis Bencana,Rusak Berat,Rusak Sedang,Rusak Ringan,Terendam
0,101,Banjir,1381,372,3053,265376
1,102,Tanah Longsor,619,532,1118,0
2,103,Banjir dan Tanah Longsor,5,1,20,0
3,104,Gelombang Pasang,64,44,36,26580
4,105,Putting Beliung,2170,3520,13240,0
5,106,Kekeringan,0,0,0,0
6,107,Kebakaran Hutan,1,0,1,0
7,108,Gempa Bumi,77026,35859,113786,0
8,109,Tsunami,1583,70,1099,0
9,110,Gempa Bumi dan Tsunami,68451,0,0,0
10,111,Letusan Gunung Api,0,0,0,0

In [157]:
#Menggabungkan 3 data fasilitas, rumah dan korbanjiwa berdasarkan kode bencana dan jenis bencana
data=pd.merge(fasilitas,rumah,how='left',on=['Kode Bencana','Jenis Bencana'])
datafinal=pd.merge(data,korbanjiwa,how='left',on=['Kode Bencana','Jenis Bencana'])
datafinal

,Kode Bencana,Jenis Bencana,Kesehatan,Peribadatan,Pendidikan,Rusak Berat,Rusak Sedang,Rusak Ringan,Terendam,Meninggal & Hilang,Luka-luka,Menderita & mengungsi
0,101,Banjir,35,349,443,1381,372,3053,265376,119,297,1453803
1,102,Tanah Longsor,7,27,26,619,532,1118,0,167,142,38198
2,103,Banjir dan Tanah Longsor,0,0,0,5,1,20,0,0,0,0
3,104,Gelombang Pasang,0,9,2,64,44,36,26580,0,5,114829
4,105,Putting Beliung,10,72,96,2170,3520,13240,0,24,228,16019
5,106,Kekeringan,0,0,0,0,0,0,0,0,0,7798693
6,107,Kebakaran Hutan,0,0,0,1,0,1,0,4,4,586
7,108,Gempa Bumi,38,113,1005,77026,35859,113786,0,572,2002,483399
8,109,Tsunami,0,0,0,1583,70,1099,0,453,14059,41132
9,110,Gempa Bumi dan Tsunami,22,327,265,68451,0,0,0,3475,4438,221450
10,111,Letusan Gunung Api,0,0,0,0,0,0,0,0,56,71424

In [158]:
#Menjadikan Kode Bencana sebagai index
datafinal2=datafinal.set_index('Kode Bencana')
datafinal2

,Jenis Bencana,Kesehatan,Peribadatan,Pendidikan,Rusak Berat,Rusak Sedang,Rusak Ringan,Terendam,Meninggal & Hilang,Luka-luka,Menderita & mengungsi
Kode Bencana,,,,,,,,,,,
101,Banjir,35,349,443,1381,372,3053,265376,119,297,1453803
102,Tanah Longsor,7,27,26,619,532,1118,0,167,142,38198
103,Banjir dan Tanah Longsor,0,0,0,5,1,20,0,0,0,0
104,Gelombang Pasang,0,9,2,64,44,36,26580,0,5,114829
105,Putting Beliung,10,72,96,2170,3520,13240,0,24,228,16019
106,Kekeringan,0,0,0,0,0,0,0,0,0,7798693
107,Kebakaran Hutan,0,0,0,1,0,1,0,4,4,586
108,Gempa Bumi,38,113,1005,77026,35859,113786,0,572,2002,483399
109,Tsunami,0,0,0,1583,70,1099,0,453,14059,41132
110,Gempa Bumi dan Tsunami,22,327,265,68451,0,0,0,3475,4438,221450
111,Letusan Gunung Api,0,0,0,0,0,0,0,0,56,71424

In [155]:
#Memunculkan datafinal2 hanya 5 data teratas
datafinal2.head()

,Jenis Bencana,Kesehatan,Peribadatan,Pendidikan,Rusak Berat,Rusak Sedang,Rusak Ringan,Terendam,Meninggal & Hilang,Luka-luka,Menderita & mengungsi
Kode Bencana,,,,,,,,,,,
101,Banjir,35,349,443,1381,372,3053,265376,119,297,1453803
102,Tanah Longsor,7,27,26,619,532,1118,0,167,142,38198
103,Banjir dan Tanah Longsor,0,0,0,5,1,20,0,0,0,0
104,Gelombang Pasang,0,9,2,64,44,36,26580,0,5,114829
105,Putting Beliung,10,72,96,2170,3520,13240,0,24,228,16019

In [156]:
#Memunculkan datafinal2 hanya 5 data belakang
datafinal2.tail()

,Jenis Bencana,Kesehatan,Peribadatan,Pendidikan,Rusak Berat,Rusak Sedang,Rusak Ringan,Terendam,Meninggal & Hilang,Luka-luka,Menderita & mengungsi
Kode Bencana,,,,,,,,,,,
107,Kebakaran Hutan,0,0,0,1,0,1,0,4,4,586
108,Gempa Bumi,38,113,1005,77026,35859,113786,0,572,2002,483399
109,Tsunami,0,0,0,1583,70,1099,0,453,14059,41132
110,Gempa Bumi dan Tsunami,22,327,265,68451,0,0,0,3475,4438,221450
111,Letusan Gunung Api,0,0,0,0,0,0,0,0,56,71424

In [164]:
#Menambahkan column Total Kerusakan pada Fasilitas, korbanjiwa dan rumah
datafinal2['Total Fasilitas'] =(datafinal2['Kesehatan']+datafinal2['Peribadatan']+datafinal2['Pendidikan'])
datafinal2['Total Korban Jiwa'] =(datafinal2['Meninggal & Hilang']+datafinal2['Luka-luka']+datafinal2['Menderita & mengungsi'])
datafinal2['Total Rumah'] =(datafinal2['Rusak Berat']+datafinal2['Rusak Sedang']+datafinal2['Rusak Ringan']+datafinal2['Terendam'])
datafinal2

,Jenis Bencana,Kesehatan,Peribadatan,Pendidikan,Rusak Berat,Rusak Sedang,Rusak Ringan,Terendam,Meninggal & Hilang,Luka-luka,Menderita & mengungsi,Total Fasilitas,Total Korban Jiwa,Total Rumah
Kode Bencana,,,,,,,,,,,,,,
101,Banjir,35,349,443,1381,372,3053,265376,119,297,1453803,827,1454219,270182
102,Tanah Longsor,7,27,26,619,532,1118,0,167,142,38198,60,38507,2269
103,Banjir dan Tanah Longsor,0,0,0,5,1,20,0,0,0,0,0,0,26
104,Gelombang Pasang,0,9,2,64,44,36,26580,0,5,114829,11,114834,26724
105,Putting Beliung,10,72,96,2170,3520,13240,0,24,228,16019,178,16271,18930
106,Kekeringan,0,0,0,0,0,0,0,0,0,7798693,0,7798693,0
107,Kebakaran Hutan,0,0,0,1,0,1,0,4,4,586,0,594,2
108,Gempa Bumi,38,113,1005,77026,35859,113786,0,572,2002,483399,1156,485973,226671
109,Tsunami,0,0,0,1583,70,1099,0,453,14059,41132,0,55644,2752
110,Gempa Bumi dan Tsunami,22,327,265,68451,0,0,0,3475,4438,221450,614,229363,68451
111,Letusan Gunung Api,0,0,0,0,0,0,0,0,56,71424,0,71480,0

In [173]:
# Ordering variable/column
datafinal3 = datafinal2[['Jenis Bencana', 'Kesehatan', 'Peribadatan','Pendidikan','Total Fasilitas',
                         'Rusak Berat','Rusak Sedang','Rusak Ringan','Terendam','Total Rumah',
                        'Meninggal & Hilang','Luka-luka','Menderita & mengungsi','Total Korban Jiwa']]
datafinal3

,Jenis Bencana,Kesehatan,Peribadatan,Pendidikan,Total Fasilitas,Rusak Berat,Rusak Sedang,Rusak Ringan,Terendam,Total Rumah,Meninggal & Hilang,Luka-luka,Menderita & mengungsi,Total Korban Jiwa
Kode Bencana,,,,,,,,,,,,,,
101,Banjir,35,349,443,827,1381,372,3053,265376,270182,119,297,1453803,1454219
102,Tanah Longsor,7,27,26,60,619,532,1118,0,2269,167,142,38198,38507
103,Banjir dan Tanah Longsor,0,0,0,0,5,1,20,0,26,0,0,0,0
104,Gelombang Pasang,0,9,2,11,64,44,36,26580,26724,0,5,114829,114834
105,Putting Beliung,10,72,96,178,2170,3520,13240,0,18930,24,228,16019,16271
106,Kekeringan,0,0,0,0,0,0,0,0,0,0,0,7798693,7798693
107,Kebakaran Hutan,0,0,0,0,1,0,1,0,2,4,4,586,594
108,Gempa Bumi,38,113,1005,1156,77026,35859,113786,0,226671,572,2002,483399,485973
109,Tsunami,0,0,0,0,1583,70,1099,0,2752,453,14059,41132,55644
110,Gempa Bumi dan Tsunami,22,327,265,614,68451,0,0,0,68451,3475,4438,221450,229363
111,Letusan Gunung Api,0,0,0,0,0,0,0,0,0,0,56,71424,71480